bundled_packages_dir: packages
data_dir: data
description: Generate text from a prompt with this thirteen billion parameter language model.
environment_variables: {}
examples_filename: examples.yaml
external_package_dirs: []
input_type: Any
live_reload: false
model_class_filename: model.py
model_class_name: Model
model_framework: custom
model_metadata:
  example_model_input: {"prompt": "Describe the Section 302 in IPC", "temperature": 0.1, "top_p": 0.75,"num_beams": 4}
  avatar_url: https://cdn.baseten.co/production/static/explore/meta.png
  cover_image_url: https://cdn.baseten.co/production/static/explore/llama.png
  tags:
  - text-generation
model_module_dir: model
model_name: legalassistr-13b
model_type: custom
python_version: py311
requirements:
- accelerate==0.22.0
- bitsandbytes==0.41.1
- einops==0.6.1
- faker==19.3.1
- hf-transfer==0.1.4
- peft==0.5.0
- protobuf==3.20.3
- safetensors==0.3.3
- scipy==1.10.1
- sentencepiece==0.1.99
- torch==2.0.1
- transformers==4.32.1
resources:
  cpu: "3"
  memory: 23gi
  use_gpu: true
  accelerator: L4
secrets:
  hf_access_token: "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"
spec_version: '2.0'
system_packages: []